//! Sanity tests for the export pipeline against the synthetic v1
//! fixture. Confirm each bundled template renders without error and
//! that the trainer scaffold contains the structural marks we want.

use atlas_core::export::{build_context, load_template, render_to_string, AtlasSidecar, Selection};
use atlas_core::storage::Db;
use atlas_parser_trait::{NullReporter, SdkParser};
use atlas_parser_ue::Dumper7Parser;
use std::path::PathBuf;

fn fixture_v1() -> PathBuf {
    let mut p = PathBuf::from(env!("CARGO_MANIFEST_DIR"));
    p.pop();
    p.pop();
    p.push("fixtures");
    p.push("synthetic");
    p.push("tiny-game-v1");
    p
}

fn db_with_v1() -> (tempfile::TempDir, Db, i64, Vec<String>) {
    let tmp = tempfile::tempdir().unwrap();
    let mut db = Db::open(tmp.path().join("atlas.sqlite")).unwrap();
    let g = Dumper7Parser::new()
        .parse(&fixture_v1(), &NullReporter)
        .unwrap();
    let report = db.ingest(&g).unwrap();

    // Pull a handful of field ids to feed the export — pick the
    // first 5 fields under TinyGame.APawn.
    let ids: Vec<String> = {
        let mut stmt = db
            .conn
            .prepare(
                "SELECT id FROM symbols
                 WHERE dump_id = ? AND kind = 6
                 ORDER BY fqn LIMIT 5",
            )
            .unwrap();
        stmt.query_map([report.dump_id], |r| r.get::<_, Vec<u8>>(0))
            .unwrap()
            .map(|r| hex(&r.unwrap()))
            .collect()
    };
    (tmp, db, report.dump_id, ids)
}

fn hex(b: &[u8]) -> String {
    b.iter().map(|x| format!("{x:02x}")).collect()
}

#[test]
fn trainer_template_renders_with_atlas_marks() {
    let (_tmp, db, dump_id, ids) = db_with_v1();
    let (src, _) = load_template("Trainer.cs").unwrap();
    let ctx = build_context(
        &db,
        dump_id,
        &ids,
        "TinyTrainer",
        "TinyGameTrainer",
        "TinyGame-Win64-Shipping",
    )
    .unwrap();
    let out = render_to_string("Trainer.cs", &src, ctx).unwrap();
    assert!(out.contains("Generated by Codex Atlas"));
    assert!(out.contains("class TinyGameTrainer"));
    assert!(out.contains("TinyGame-Win64-Shipping"));
    assert!(out.contains("CheatEntry"));
    assert!(out.contains("cheats.Add(new CheatEntry"));
    // The scaffold should leave BaseOffset = 0x0 with the TODO note.
    assert!(out.contains("TODO: fill in module-relative base"));
}

#[test]
fn offsets_template_renders_with_constexpr_lines() {
    let (_tmp, db, dump_id, ids) = db_with_v1();
    let (src, _) = load_template("Offsets.h").unwrap();
    let ctx = build_context(&db, dump_id, &ids, "p", "X", "x").unwrap();
    let out = render_to_string("Offsets.h", &src, ctx).unwrap();
    assert!(out.contains("namespace AtlasOffsets"));
    assert!(out.contains("static constexpr std::uint32_t"));
}

#[test]
fn ida_mapping_template_renders_tab_separated() {
    let (_tmp, db, dump_id, ids) = db_with_v1();
    let (src, _) = load_template("IDA-Mapping").unwrap();
    let ctx = build_context(&db, dump_id, &ids, "p", "X", "x").unwrap();
    let out = render_to_string("IDA-Mapping", &src, ctx).unwrap();
    assert!(out.contains("Codex Atlas IDA mapping"));
    assert!(out.contains("\t"));
}

#[test]
fn sidecar_records_template_hash_and_symbols() {
    let sel = Selection {
        symbol_ids_hex: vec!["aa".repeat(16)],
        rules: Default::default(),
    };
    let s = AtlasSidecar::build("0.4.0", "TinyGame", "1.0", 1, "Trainer.cs", "hello", &sel);
    assert_eq!(s.symbols, vec!["aa".repeat(16)]);
    assert!(s.template_version.starts_with("blake3:"));
}
